// Auto-generated by tools/generate-test-manifest.js
window.TEST_MANIFEST = {
  "version": "0.0.1-split-tests-2-0ff16fe-20250810T153942",
  "files": [
    "tests/core/cell-toggle.test.js",
    "tests/core/grid-initialization.test.js",
    "tests/core/movement.test.js",
    "tests/core/neighbour-counting.test.js",
    "tests/core/simulation-creation.test.js",
    "tests/features/simulation-features.test.js",
    "tests/integration/control-management.test.js",
    "tests/integration/integration.tests.js",
    "tests/integration/modal-manager.test.js",
    "tests/integration/modal-template-manager.test.js",
    "tests/interaction/drag-coordinate-fix.test.js",
    "tests/interaction/drag-toggle.test.js",
    "tests/performance/more-performance.test.js",
    "tests/performance/performance.test.js",
    "tests/system/system.tests.js",
    "tests/system/test-utilities.test.js",
    "tests/ui/config-validator.test.js",
    "tests/ui/shared-components.test.js",
    "tests/ui/ui.tests.js",
    "tests/visual/colour.tests.js"
  ]
}
